version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          app-dir: ~/server 
          cache-only-lockfile: true 
          check-cache: never 
          include-branch-in-cache-key: true 
          pkg-manager: npm 
          with-cache: true 
workflows:
    example-workflow:
      jobs:
        - example-job
        - node/run:
            app-dir: ~/server 
            npm-run: npm start 
