version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test:
    working_directory: ~/server
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: |
            cd server && npm install
          name: install npm dependencies
      - run:
          command: |
            cd server && npm run test
          name: run test
workflows:
  build_test:
    jobs:
      - build_and_test